### ISSUE TITLE
`calibrate_sim` examples and vignette are very long-running

### ISSUE THREAD

**Issue by jsta** [hdugan/glmtools#12]
I propose turning off the last execution step of the `calibrate_sim` examples and possibly building a static version of the associated vignette (We've done this with LAGOS R packages using the `R.rsp` package: https://cran.r-project.org/web/packages/R.rsp/vignettes/R_packages-Static_PDF_and_HTML_vignettes.pdf) to reduce package checking resources.

**Comment by hdugan** [comment]
Think it's a great idea. If you are familiar with implementing that, are you ok making the change?

**Comment by jsta** [comment]
Yep, I already pushed a fix to the open PR turning off the `calibrate_sim` example execution. Haven't done anything with the vignette yet.
